name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create stub model file for image build
        run: |
          if [ ! -f best_model.pth ]; then
            # Create a tiny placeholder so the COPY instruction in Dockerfile succeeds
            echo "stub model" > best_model.pth
          fi

      - name: Build image
        run: docker build --build-arg MODEL_URL= -t anime-or-not-api:ci .


